[phases.build]
nixPkgs = ['php83', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'nodejs_20']

[phases.setup]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm install',
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}'
